- hosts: webserver
  
  tasks:
  - name: Creation directory for mounting DVD
    file:
      path: /rhel8
      state: directory
  - name: Mount DVD 
    mount:
      path: /rhel8
      src: /dev/sr0
      fstype: iso9660
      opts: ro
      state: present
  - name: Repo for OS Soft 1
    yum_repository:
      name: repo1
      description: Yum repository for RHEL 8 Softwares
      baseurl: /rhel8/AppStream
      gpgcheck: 0
  - name: Repo for OS Soft 2
    yum_repository:
      name: repo2
      description: Yum repository for RHEL 8 Softwares
      baseurl: /rhel8/BaseOS
      gpgcheck: 0
  - name: Docker Repository
    yum_repository:
         description: Repo for docker
         name: docker-ce
         baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
         gpgcheck: no
  - name: installing docker
    command: "yum install docker-ce --nobest -y"
  - name: starting docker services
    service:
          name: docker
          state: started   
          enabled: yes
  - name: installating docker SDK
    command: "pip3 install docker"    
  - name: Creating directory
    file:
          path: /webpages
          state: directory
  - name: copying webpage to managed node directory
    copy:
          src: index.html
          dest: /webpages
  - name: Deploying Container with running webserver
    docker_container:
           name: httpd
           image: "httpd"
           state: started
           exposed_ports: 80
           ports: 8082:80
           volumes: /webpages:/usr/local/apache2/htdocs



