- hosts: webserver
  tasks:
  - name: ansible create directory
    file:
      path: /rhel8
      state: directory
  - name: Repo for OS 
    yum_repository:
      name: Repo 1
      description: Yum repository for RHEL 8 Softwares
      baseurl: /rhel8/AppStream
      gpgcheck: 0
  - name: Repo for OS 2
    yum_repository:
      name: Repo 2
      description: Yum repository for RHEL 8 Softwares
      baseurl: /rhel8/BaseOS
      gpgcheck: 0