- hosts: webserver
  
  tasks:
  - name: installating docker SDK
    command: "pip3 install docker"    
  - name: Creating directory
    file:
          path: /webpages
          state: directory
  - name: copying webpage to managed node directory
    copy:
          src: index.html
          dest: /webpages
  - name: Deploying Container with running webserver
    docker_container:
           name: httpd
           image: "httpd"
           state: started
           exposed_ports: 80
           ports: 8082:80
           volumes: /webpages:/usr/local/apache2/htdocs